retrieval:
  persist-dir: /home/iordanissapidis/KG-RAG/examples/WC2014QA/persist
  topk: 10
  score-threshold: 0.4



generation:
  prompts:
    system: "Respond to all questions directly without any explanation"

    rag_prompt: >
      Your task is to extract the answer from the documents. There is always relevant information present.
      Find the entity mentioned in the question, then extract the specific information requested about that entity from the documents.
      Answer with only the exact word or name needed.
      Use only text that appears in the documents.
      Never respond with "None" - always extract something relevant from the text.
      If there are multiple answers, only provide one - the most fitting.

    kgrag_prompt: >
      Your task is to extract the answer from the documents. There is always relevant information present.
      Find the entity mentioned in the question, then extract the specific information requested about that entity from the documents.
      Answer with only the exact word or name needed.
      Use only text that appears in the documents.
      Never respond with "None" - always extract something relevant from the text.
      If there are multiple answers, only provide one - the most fitting.



  
  # model: gemma3:12b
  temperature: 0.05