ingestion:
  embedding-model: nomic-embed-text
  persist-dir: examples/vectorstore
  # persist-dir: /mnt/10TB/iordanissapidis/datasets/vectorstore
  dataset-dir: examples/datasets/MarineRestorationAnalysis # uncomment to index a new dataset
  # dataset-dir: /mnt/10TB/iordanissapidis/datasets/large

retrieval:
  topk: 5
  score-threshold: 0.4
  embedding-model: nomic-embed-text
  persist-dir: examples/vectorstore



generation:
  prompts:
    system: "Respond to all questions in a concise and direct manner"

    # Low quality/irrelevant/noisy data
    rag_prompt: >
      Answer according to your knowledge and, if needed, the given facts. 
      If the data is irrelevant, ignore it and answer according to your knowledge.
      Do NOT mention that you were given any data or information in your response. 
      You are given the following data:

  model: llama3.1:8b
  temperature: 0
