retrieval:
  persist-dir: /home/iordanissapidis/KG-RAG/examples/MetaQA_evaluation/persist
  topk: 15
  score-threshold: 0.4



generation:
  prompts:
    system: "Respond to all questions directly without any explanation"

    rag_prompt: >
      Examine all the provided data carefully and answer only according to that data.  
      Respond with a single word, name, or date—*only the exact answer required by the question*.  
      Identify the entity requested in the question and ignore all data not directly mentioning that entity.  
      Do not include additional details such as dates, descriptions, or extra context.  
      If multiple answers are needed, separate them using the character | (e.g., X | Y | Z).